services:

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: date-picker
      POSTGRES_DB: dev
    volumes:
      - date-picker:/var/lib/postgresql/data

volumes:
  date-picker:
